# Prometheus configuration for Smart Toll Cache System

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'toll-management-service-1'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['toll-management-service-1:9080']

  - job_name: 'toll-management-service-2'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['toll-management-service-2:9080']

  - job_name: 'toll-management-service-3'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['toll-management-service-3:9080']
